apiVersion: v1
kind: ConfigMap
metadata:
  name: api-unidex-env
data:
  NODE_ENV: "production"
  DB_URL: "mongodb://admin:123@mongo-unidex:27018"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-unidex
spec:
  selector:
    matchLabels:
      app: api-unidex
  template:
    metadata:
      labels:
        app: api-unidex
    spec:
      containers:
      - name: api-unidex
        image: luanbatistadev/unidex-api:latest
        envFrom:
        - configMapRef:
            name: api-unidex-env
        resources: {}
        ports:
        - containerPort: 3034
---
apiVersion: v1
kind: Service
metadata:
  name: api-unidex-service
spec:
  type: NodePort
  selector:
    app: api-unidex
  ports:
  - port: 3034
    targetPort: 3034
    nodePort: 30334